### ISSUE TITLE
Missing the database.

### ISSUE THREAD

**Issue by sthasagar19** [avishekhbharati/PharmAssistant#1]
You need to insert the database in the App_Data folder.

**Comment by dhanaseelanrkiwis1982** [comment]
can you please share the database for this application?

**Comment by avishekhbharati** [comment]
What the problem with you guys ?? Its "code first". Don't just jump into copying and expect to to run everything.

**Comment by sthasagar19** [comment]
LOL .. reply in  a year. Well the code without database is useless and again if you don't want anyone to copy your code make it private repo bro.

**Comment by avishekhbharati** [comment]
Don't make fun of yourself. Please, enlighten yourself first:
https://www.youtube.com/watch?v=kbH-rqMl8cE

**Comment by avishekhbharati** [comment]
Hope this will help you to understand about absence of database.
https://www.youtube.com/watch?v=kbH-rqMl8cE
Good luck. :)

**Comment by prabathsingh101** [comment]
But login problem how to login and how to create uid n pwd

**Comment by prabathsingh101** [comment]
What will be table use for login, in this project membership table is used, and I how to use membership table for login

**Comment by prabathsingh101** [comment]
First page is running login page, but how to login uid pwd, please suggest me, and how to create membership table for this PharmAssistant project.

**Comment by Gauravsurbhi** [comment]
H bro..humble request...plz share me database script.... cool.gaurav7@gmail.com
